spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/buildforge
    username: user
    password: password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

kafka:
  host: "localhost:9092"
  topics:
    users:
      created: user-created-topic
      deleted: user-deleted-topic
  group:
    users:
      created: user-created-group
      deleted: user-deleted-group